const
  DropBoxAppkey = '';
  DropBoxAppSecret = '';

  WinLiveClientID = '';
  WinLiveClientSecret = '';

  GoogleAppKey = '494112256923-r3j76nefc21jnli6osumv5p8dro5qeg4.apps.googleusercontent.com';
  GoogleAppSecret = 'lxsTV-P-xR09EI6CERjG_yjk';

  BoxNetAppKey = '';
  BoxNetAppSecret = '';

  BitCasaAppKey = '';
  BitCasaAppSecret = '';

  AmazonCloudDriveAppKey = '';
  AmazonCloudDriveAppSecret = '';
  AmazonCloudDriveCallBack = '';

  HubicAppKey = '';
  HubicAppSecret = '';
  HubicCallBack = '';

  HiDriveAppKey = '';
  HiDriveAppSecret = '';

  YandexDiskAppKey = '';
  YandexDiskAppSecret = '';
